name: dbt_run_heal_models
run-name: dbt_run_heal_models

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Heal Models
      command: |
        dbt run -m "$PROJECT_NAME,tag:heal" "fsc_evm,tag:heal" --vars '{"HEAL_MODEL":True}'
    secrets: inherit